"use client"

import type { Metadata } from 'next'
import './globals.sass'
import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from '@/common/check-route'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import Provider from '@/components/config/Provider'
import { UserProvider } from '@/common/utils/userContext'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const metadata: Metadata = {
    title: 'Academy Services App',
    description: 'Generated by create next app',
  }

  // Get the current path of application
  const path = usePathname()

  // Verify if the route is public
  const isPublic = checkIsPublicRoute(path)

  return (
    <html lang="en">
      <body>
        <Provider>
          {isPublic && (
            <UserProvider>
              <Navbar />
              <main className='pt-[150px] selection:bg-[#F2921D] selection:text-white'>
                {children}
              </main>
              <Footer />
            </UserProvider>
          )}

          {!isPublic && (
            <UserProvider>
              <Navbar />
              <main className='pt-[150px] selection:bg-[#F2921D] selection:text-white'>
                {children}
              </main>
              <Footer />
            </UserProvider>
          )}
        </Provider>
      </body>
    </html>
  )
}
