"use client"

import type { Metadata } from 'next'
import './globals.css'
import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from '@/common/check-route'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const metadata: Metadata = {
    title: 'Academy Services App',
    description: 'Generated by create next app',
  }

  // Get the current path of application
  const path = usePathname()

  // Verify if the route is public
  const isPublic = checkIsPublicRoute(path)

  return (
    <html lang="en">
      <body>
        {isPublic && (
          <>
            <Navbar />
            <main>
              {children}
            </main>
            <Footer />
          </>
        )}

        {!isPublic && (
          <>
            <Navbar />
            <main>
              {children}
            </main>
            <Footer />
          </>
        )}
      </body>
    </html>
  )
}
